services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=xzam
      - POSTGRES_USER=xzam
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp:
